#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	{% for job in jobs %}
	@echo "{{job.name}}{{job.spacing}}{{job.description}}"
	{% endfor %}
	{% for target in targets %}
	@echo "{{target.name}}{{target.spacing}}{{target.description}}"
	{% endfor %}
	{% for job in bsub_jobs %}
	@echo "{{job.name}}{{job.spacing}}{{job.description}}"
	{% endfor %}
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------

{% for job in jobs %}
#----------------------------------------------------------
# Target "{{job.name}}" 
#----------------------------------------------------------
{{job.name}}: {{ job.dependencies|join(" ") }}
	{% for action in job.actions %}
	{{action}}	
	{% endfor %}
.PHONY: {{job.name}}
#----------------------------------------------------------

{% endfor %}
{% for target in targets %}
#----------------------------------------------------------
# Target "{{target.name}}" 
#----------------------------------------------------------
{% if target.outputs %}
{{target.name}}: {{target.outputs|join(" ")}}

{{target.outputs|join(" ")}} : {{ target.dependencies|join(" ") }}
	{% for action in target.actions %}
	{{action}}	
	{% endfor %}
{% else %}
{{target.name}}: {{ target.dependencies|join(" ") }}
	{% for action in target.actions %}
	{{action}}	
	{% endfor %}
.PHONY: {{target.name}}
{% endif %}
#----------------------------------------------------------

{% endfor %}
{% for job in bsub_jobs %}
#----------------------------------------------------------
# BSUB Target "{{job.name}}" 
#----------------------------------------------------------
{{job.name}}: {{ job.dependencies|join(" ") }}
	{% for action in job.actions %}
	{{action}}
	{% endfor %}
.PHONY: {{job.name}}
#----------------------------------------------------------

{% endfor %}
